[tool.pdm]

[project]
name = "MCSL2"
version = "2.0.0b1"
description = "A Minecraft Server Launcher"
authors = [{ name = "LxHTT", email = "lxhtz.dl@qq.com" }]
dependencies = []
requires-python = ">=3.8,<3.10"
license = { text = "GPL-3.0" }

[tool.black]
extend-exclude = "(MCSL2_Icon.py)"
